Praxis.App/Controllers/CatalogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Praxis.App.Helpers;
using Praxis.Business.DAL;
using Praxis.Business.Helpers;
using Praxis.Model.Emun;
using Praxis.Model.ViewModel;

namespace Praxis.App.Controllers
{
    public class CatalogosController : Controller
    {
        // GET: Catalogos
        public ActionResult Index()
        {
            return View();
        }
        //--------------------------------------------------------------------------------------------
        #region Usuarios
        public ActionResult Usuarios()
        {
            ViewBag.IdPantalla = Convert.ToInt32(EnumPantalla.Usuarios);
            return View();
        }
        //--------------------------------------------------------------------------------------------
        public JsonpResult ObtenerUsuarios()
        {
            var lstUsers = UserDAL.ObtenerUsuarios();
            return this.Jsonp(lstUsers);
        }
        //--------------------------------------------------------------------------------------------
        public ActionResult InformacionUsuarios(string idUsuario)
        {
            ViewBag.IdSubSubModule = Convert.ToInt32(EnumPantalla.Usuarios);
            ViewBag.Title = "Información Usuarios";
            if (String.IsNullOrEmpty(idUsuario))
            {
                ViewBag.Mov = "NUEVO";
                return View(new UsuariosViewModel());
            }

            #region Recuperamos al usuario
            var idUser = Guid.Parse(idUsuario);
            var UserName = UserDAL.ObtenerUsuarioVM(idUser);
            if (UserName == null)
            {
                throw new HttpException((int)System.Net.HttpStatusCode.InternalServerError, "El usuario no existe.");
            }
            #endregion

            ViewBag.Mov = "EDITAR";
            return View(UserName);
        }
        //--------------------------------------------------------------------------------------------
        [HttpPost, ValidateInput(false)]
        public JsonResult CrearUsuario(UsuariosViewModel _UsersViewModel, HttpPostedFileBase ArchivoFoto)
        {
            #region Creacion del usuario
            string path = Server.MapPath("~/Content/Img/Usuarios/");
            var _Operation = UserDAL.CrearUsuario(_UsersViewModel, ((ArchivoFoto == null) ? null : ArchivoFoto.InputStream),
                ((ArchivoFoto == null) ? "" : System.IO.Path.GetExtension(ArchivoFoto.FileName)), path);
            #endregion

            #region JsonResult
            if (_Operation.IsSuccess == EnumOperationResult.Success)
            {
                var _Data = (UsuariosViewModel)_Operation.Data;
                #region Envio de correo
                var oMail = MailDAL.ObtenerMail(EnumCatMail.ActivacionCuenta);
                var sUrl = Request.ServerVariables["HTTP_HOST"].ToString() + new UrlHelper(Request.RequestContext).Action("LoginTemp", "Login", new { id = _Data.Folio });
                string sHTML = oMail.ContenidoHTML;
                sHTML = sHTML.Replace("[Nombre]", _UsersViewModel.Nombre);
                sHTML = sHTML.Replace("[href]", sUrl);
                MailHelper.enviaCorreo(_UsersViewModel.Correo, oMail.BCC, oMail.BCCO, oMail.Asunto, sHTML);

                //REGISTRO DE ALTA DE REGISTRO
                #region RegistroNavegacion
                Guid _IdFolio = Guid.NewGuid();
                var BitacoraOperation = BitacoraDAL.RegistroBitacoraNavegacion(_UsersViewModel, Convert.ToInt32(EnumPantalla.Usuarios), Convert.ToInt32(EnumCatEvento_Bitacora.Alta_de_Registro), "0", "IdUsuario", _Data.IdUsuarioGuid.ToString(), "", _UsersViewModel.Correo + "," + _UsersViewModel.Nombre, _IdFolio.ToString());
                if (BitacoraOperation.IsSuccess == EnumOperationResult.Failure)
                    return Json(OperationResult.Failure(_Operation.Message + "\n" + BitacoraOperation.Message));
                #endregion

                return Json(OperationResult.Success(_Operation.Message));
                #endregion
            }
            else
            {
                return Json(OperationResult.Failure(_Operation.Message));
            }
            #endregion
        }
        //--------------------------------------------------------------------------------------------
        [HttpPost, ValidateInput(false)]
        public JsonResult EditarUsuario(UsuariosViewModel _UsersViewModel, HttpPostedFileBase ArchivoFoto)
        {

            #region Editar datos del usuario
            string path = Server.MapPath("~/Content/Img/Usuarios/");
            var _Operation = UserDAL.EditarUsuario(_UsersViewModel, ((ArchivoFoto == null) ? null : ArchivoFoto.InputStream),
                                ((ArchivoFoto == null) ? "" : System.IO.Path.GetExtension(ArchivoFoto.FileName)), path);
            #endregion

            #region JsonResult
            if (_Operation.IsSuccess == EnumOperationResult.Success)
            {
                return Json(OperationResult.Success(_Operation.Message));
            }
            else
            {
                return Json(OperationResult.Failure(_Operation.Message));
            }
            #endregion
        }
        //--------------------------------------------------------------------------------------------
        public JsonResult EliminarUsuario(string IdUsuario)
        {
            #region Eliminar usuario
            var _Operation = UserDAL.BorrarUsuario(IdUsuario);
            #endregion

            #region JsonResult
            if (_Operation.IsSuccess == EnumOperationResult.Success)
            {
                return Json(OperationResult.Success(_Operation.Message));
            }
            else
            {
                return Json(OperationResult.Failure(_Operation.Message));
            }
            #endregion

        }
        //--------------------------------------------------------------------------------------------
        public ActionResult ObtenerPerfilUsuario(Guid IdUsuario)
        {
            var UsuarioVM = UserDAL.ObtenerUsuarioVM(IdUsuario);
            if (UsuarioVM.NombreRol == "Medico")
            {
                var PerfilUsuario = UserDAL.ObtenerPerfilUsuarioVM(IdUsuario);
                return this.Jsonp(PerfilUsuario);
            }
            else
            {
                return Json(new object[] { new object() }, JsonRequestBehavior.AllowGet);
            }

        }
        //--------------------------------------------------------------------------------------------
        #endregion

        #region Áreas
        public JsonpResult ObtenerAreas()
        {
            var lstAreas = CatalogosDAL.ObtenerAreas();
            return this.Jsonp(lstAreas);
        }
        //--------------------------------------------------------------------------------------------
        #endregion

        #region Roles
        public JsonpResult ObtenerRoles()
        {
            var lstAreas = CatalogosDAL.ObtenerRoles();
            return this.Jsonp(lstAreas);
        }
        //--------------------------------------------------------------------------------------------
        #endregion

        #region Estatus Usuario
        public JsonpResult ObtenerEstatusUsuario()
        {
            var lstAreas = CatalogosDAL.ObtenerEstatusUsuario();
            return this.Jsonp(lstAreas);
        }
        //--------------------------------------------------------------------------------------------
        #endregion

        #region Institución
        public JsonpResult ObtenerInstitucion()
        {
            var lstInstitucion = CatalogosDAL.ObtenerInstitucion();
            return this.Jsonp(lstInstitucion);
        }
        //--------------------------------------------------------------------------------------------
        #endregion

        #region Sexo
        public JsonpResult ObtenerSexo()
        {
            var lstInsFin = CatalogosDAL.ObtenerSexo();
            return this.Jsonp(lstInsFin);
        }
        //--------------------------------------------------------------------------------------------
        public ActionResult ObtenerSexoSelect2()
        {
            var lstInsFin = CatalogosDAL.ObtenerSexo();
            var modificarData = lstInsFin.Select(x => new
            {
                id = x.IdSexo,
                text = x.NombreSexo
            });
            return Json(new { items = modificarData }, JsonRequestBehavior.AllowGet);
        }
        //--------------------------------------------------------------------------------------------
        public ActionResult ObtenerSexoPorIdSelect2(int IdSexo)
        {
            var lstInsFin = CatalogosDAL.ObtenerSexoPorId(IdSexo);
            var modificarData = lstInsFin.Select(x => new
            {
                id = x.IdSexo,
                text = x.NombreSexo
            });
            return Json(new { items = modificarData }, JsonRequestBehavior.AllowGet);
        }
        //--------------------------------------------------------------------------------------------
        #endregion

        #region Religión
        public JsonpResult ObtenerReligion()
        {
            var lstInsFin = CatalogosDAL.ObtenerReligion();
            return this.Jsonp(lstInsFin);
        }
        //--------------------------------------------------------------------------------------------
        public ActionResult ObtenerReligionSelect2()
        {
            var lstInsFin = CatalogosDAL.ObtenerReligion();
            var modificarData = lstInsFin.Select(x => new
            {
                id = x.IdReligion,
                text = x.NombreReligion
            });
            return Json(new { items = modificarData }, JsonRequestBehavior.AllowGet);
        }
        //--------------------------------------------------------------------------------------------

Praxis.App/Views/Catalogos/Usuarios.cshtml
@{
    ViewBag.Title = "Usuarios";
}

<div class="wrapper wrapper-content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>Herramientas</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <p>
                            <span class="cssWritingAccess">
                                <a class="btn btn-success btn-outline" href="@Url.Action("InformacionUsuarios", "Catalogos")">
                                    <i class="fa fa-user-circle"></i> Nuevo usuario
                                </a>

                                <a class="btn btn-success btn-outline" id="btnExpExcelgrd">
                                    <i class="fa fa-file-excel-o"></i> Reporte excel
                                </a>

                                <a class="btn btn-success btn-outline" id="btnExpPdfgrd">
                                    <i class="fa fa-file-pdf-o"></i> Reporte PDF
                                </a>

                                <a class="btn btn-success btn-outline" id="btnLimpiarFiltros">
                                    <i class="fa fa-eraser"></i> Limpiar filtros
                                </a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div id="grdUsers"></div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="hdnIdSubSubModule" value="@ViewBag.IdSubSubModule" />
<input type="hidden" id="hdnUrlEditUser" value="@Url.Action("InformacionUsuarios", "Catalogos")" />
<input type="hidden" id="hdnUrlObtenerPerfilUsuario" value="@Url.Action("ObtenerPerfilUsuario","Catalogos")" />

<style type="text/css">
    .customer-photo {
        display: inline-block;
        width: 32px;
        height: 32px;
        border-radius: 50%;
        background-size: 32px 35px;
        background-position: center center;
        vertical-align: middle;
        line-height: 32px;
        box-shadow: inset 0 0 1px #999, inset 0 0 10px rgba(0,0,0,.2);
        margin-left: 5px;
    }

    .customer-name {
        display: inline-block;
        vertical-align: middle;
        line-height: 32px;
        padding-left: 3px;
    }

    /*.k-grid {
        width: 500px;
    }*/
</style>
@section Scripts {
    <script type="x/kendo-template" id="page-template">
        <div class="page-template">
            <div class="header">
                <div style="float: right">Pagina #: pageNum # de #: totalPages #</div>
                GAF Riesgos
            </div>
            <div class="watermark">PRAXIS</div>
            <div class="footer">
                Pagina #: pageNum # de #: totalPages #
            </div>
        </div>
    </script>
    <script src="~/Scripts/Catalogos/Usuarios.js"></script>
}